[package]
name = "chip_8"
version = "0.1.0"
authors = ["Colton C Ward <triavanicus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.10.2"
rand = "0.7.2"